[env:stm32_logger]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
debug_tool = stlink
upload_protocol = stlink
build_flags = -Wall -Wextra -Werror -fno-exceptions
lib_extra_dirs = ../../../
