name=AimNetwork
version=1.0.0
author=QRET
maintainer=QRET
sentence=Avionics Interconnected Module Network Library
paragraph=Library for communicating between avionics modules using CAN bus.
category=Communication
url=https://github.com/Queens-Rocket-Engineering-Team/av-libraries
architectures=*
includes=aim_network.h
