[env:stm32_canbus]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
debug_tool = stlink
upload_protocol = stlink

upload_flags =
    -c
    adapter serial B55B5A1A00000000DD00F001

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    ; Set HSE based on physical crystal
    -DHSE_VALUE=16000000U
    -Wall
    -Wextra
    -Werror
    -fno-exceptions

lib_deps =

; Local: points to av-libraries/ root so PlatformIO discovers AimNetwork
lib_extra_dirs = ../../../
