[env:stm32_canbus]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
debug_tool = stlink
upload_protocol = stlink
extra_scripts = pre:extra_script.py

upload_flags =
    -c

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    ; Set HSE based on physical crystal
    -DHSE_VALUE=16000000U
    -Wall
    -Wextra
    -Werror
    -fno-exceptions

lib_deps =

; Local: points to av-libraries/ root so PlatformIO discovers AimNetwork
lib_extra_dirs = ../../../
