"""
RDES Decompressor for AimFlightRecorder
Synchronized with C++ implementation (prefix-based encoding)
"""

class RDESDecompressor():
    """
    Decompresses RDES telemetry generated by AimFlightRecorder.
    Uses bit-prefixes to determine encoding length:
    - 0... (0x00): 4-byte raw 31-bit
    - 10... (0x80): 2-byte offset
    - 110... (0xC0): 3-byte offset
    - 111... (0xE0): 5-byte raw 32-bit
    """

    def __init__(self, numCols:int=8, verbose:bool=False, signedCols=[]):
        self.__numCols = numCols
        self.__verbose = verbose
        self.__signedCols = signedCols
        self.__lastDecodedVals = [0] * self.__numCols
        self.__lastCompressedSize = 0

    def decompress(self, data):
        self.__lastCompressedSize = len(data)
        decompressed = []
        curRowVals = [0] * self.__numCols
        curCol = 0
        i = 0

        while i < len(data):
            b1 = data[i]
            
            # Check for Raw 31-bit (Prefix 0)
            if (b1 & 0x80) == 0:
                val = ((data[i] & 0x7F) << 24) | (data[i+1] << 16) | (data[i+2] << 8) | data[i+3]
                i += 4
                curRowVals[curCol] = val
                self.__lastDecodedVals[curCol] = val
            
            # Check for Raw 32-bit (Prefix 111)
            elif (b1 & 0xE0) == 0xE0:
                val = (data[i+1] << 24) | (data[i+2] << 16) | (data[i+3] << 8) | data[i+4]
                i += 5
                curRowVals[curCol] = val
                self.__lastDecodedVals[curCol] = val

            # Check for 3-byte offset (Prefix 110)
            elif (b1 & 0xE0) == 0xC0:
                sign_add = (b1 & 0x10) != 0
                offset = ((b1 & 0x0F) << 16) | (data[i+1] << 8) | data[i+2]
                i += 3
                ref = self.__lastDecodedVals[curCol]
                val = (ref + offset) if sign_add else (ref - offset)
                # Keep it as uint32 bit pattern
                val &= 0xFFFFFFFF
                curRowVals[curCol] = val
                self.__lastDecodedVals[curCol] = val

            # Check for 2-byte offset (Prefix 10)
            elif (b1 & 0xC0) == 0x80:
                sign_add = (b1 & 0x20) != 0
                offset = ((b1 & 0x1F) << 8) | data[i+1]
                i += 2
                ref = self.__lastDecodedVals[curCol]
                val = (ref + offset) if sign_add else (ref - offset)
                val &= 0xFFFFFFFF
                curRowVals[curCol] = val
                self.__lastDecodedVals[curCol] = val

            else:
                # Undefined prefix
                if self.__verbose: print(f"Unknown prefix at byte {i}: {hex(b1)}")
                i += 1
                continue

            curCol += 1
            if curCol == self.__numCols:
                decompressed.append(list(curRowVals))
                curCol = 0

        return decompressed

    def getCompressedSize(self):
        return self.__lastCompressedSize
