[env:esp32_canbus]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -Wall -Wextra -Werror
    -fno-exceptions

upload_protocol = esptool

lib_deps =

; Local: points to av-libraries/ root so PlatformIO discovers AimNetwork
lib_extra_dirs = ../../../
