[env:stm32_flash]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
debug_tool = stlink
upload_protocol = stlink
build_flags = -Wall -Wextra -Werror -Wno-unused-function -fno-exceptions
lib_extra_dirs = ../../../
lib_ldf_mode = deep+
lib_deps =
