[env:stm32_canbus]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
upload_protocol = stlink

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    ; Set HSE based on physical crystal
    -DHSE_VALUE=16000000U

lib_deps =
    pazi88/STM32_CAN@1.1.2
    ; https://github.com/Queens-Rocket-Engineering-Team/av-libraries.git

; Local: points to av-libraries/ root so PlatformIO discovers AimNetwork
lib_extra_dirs = ../../../
